version: '3'
services:
  app:
    image: my_app
    build: .
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - mongodb
    networks:
      - mosaic_app_net
    volumes:
      - "./:/code"

  redis-worker:
    image: my_app
    depends_on:
      - redis
      - mongodb
    networks:
      - mosaic_app_net
    volumes:
      - "./:/code"
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - MONGODB_URI=${MONGODB_URI}
      - SECRET_KEY=${SECRET_KEY}
    command: "rq worker -c settings"

  mongodb:
    user: root
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - /opt/mongodb:/bitnami
    networks:
      - mosaic_app_net

  redis:
    image: redis:4.0.5-alpine
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - mosaic_app_net
    ports:
      - "6379:6379"

networks:
  mosaic_app_net:
    driver: bridge

